package com.example.login;

/**
 * Servlet that handles creating new products via form submission.
 * Requires an authenticated admin session ("adminUser").
 */

import entity.Product;
import entity.ProductDAO;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.*;

import java.io.IOException;
import java.sql.SQLException;

@WebServlet("/products/create")
public class ProductCreateServlet extends HttpServlet {

    private ProductDAO productsDAO = new ProductDAO();

    /**
     * Checks if an admin session exists.
     */
    private boolean isLoggedIn(HttpServletRequest request) {
        HttpSession session = request.getSession(false);
        return session != null && session.getAttribute("adminUser") != null;
    }

    /**
     * Displays the create product form.
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        if (!isLoggedIn(request)) {
            response.sendRedirect(request.getContextPath() + "/admin/login");
            return;
        }

        request.getRequestDispatcher("/product_create.jsp").forward(request, response);
    }

    /**
     * Handles form submission to create a new product.
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        if (!isLoggedIn(request)) {
            response.sendRedirect(request.getContextPath() + "/admin/login");
            return;
        }

        String name = request.getParameter("product_name");
        String description = request.getParameter("product_description");
        String color = request.getParameter("product_color");
        String size = request.getParameter("product_size");
        double price = Double.parseDouble(request.getParameter("product_price"));

        // Build a Product from submitted form fields (id is generated by DB)
        Product product = new Product(name, description, color, size, price);

        try {
            productsDAO.create(product);
        } catch (SQLException e) {
            throw new ServletException(e);
        }

        response.sendRedirect(request.getContextPath() + "/products/read");
    }
}
